# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phil's Blog - Knowledge Sharing
description: > # this means to ignore newlines until "baseurl:"
  Here is my documentation warehouse, what I learnt and what I want to share to you
repository: https://github.com/0xzphil/blog
baseurl: /blog  # the subpath of your site, e.g. /blog
url: https://0xzphil.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Phil Nguyễn
email: fizz.uet@gmail.com

navigation:
  - text: Home
    url: /
  - text: AWS Analytic
    url: /aws_analytic
  - text: AWS VPC (WIP)
    url: /aws_vpc
  - text: AWS ASG (WIP)
    url: /aws_asg
  - text: AWS Container (WIP)
    url: /aws_container

collections_dir: collections
collections:
  analytics:
    output: true
    permalink: /:collection/:path/
  aws_vpc:
    output: true
    permalink: /:collection/:path/
  asg:
    output: true
    permalink: /:collection/:path/
  aws_container:
    output: true
    permalink: /:collection/:path/

projects:
  - name: git-secret
    description: A bash-tool to store your private data inside a git repository.
    link: https://sobolevn.github.io/git-secret
    image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true
  - name: awesome-cryptography
    description: A curated list of cryptography resources and links.
    link: https://github.com/sobolevn/awesome-cryptography
    image: https://pbs.twimg.com/profile_images/751426570607271937/vGxpniun_400x400.jpg
  - name: ecto_autoslug_field
    description: Automatically creates slugs for your Ecto models.
    link: https://github.com/sobolevn/ecto_autoslug_field
  - name: django-split-settings
    description: Organize Django settings into multiple files and directories. Easily override and modify settings. Use wildcards and optional settings files.
    link: https://github.com/sobolevn/django-split-settings

social:
  - service: github
    username: 0xzphil
    link: https://github.com/0xzphil
  - service: linkedin
    username: 0xzphil
    link: https://linkedin.com/in/0xzphil/
  - service: youtube
    username: yuu.orenji
    link: https://youtube.com/@yuu.orenji
  - service: deviantart
    username: yuulya
    link: https://deviantart.com/yuulya
  - service: twitter
    username: 0xzphil
    link: https://twitter.com/0xzphil

# Plugins
gems:
  - jekyll-seo-tag
